use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AbilityType {
    None,
    Damage,
    Heal,
    Resurrect,
    Blink,
    Bonus,
    RegisterTrigger,
    SetTarget,
    Threat,
    Stun,
    Snare,
    Silence,
    RemoveType,
    SetCooldown,
    CombatResource,
    DamageShield,
    MovePosition,
    Knockback,
    Charge,
    Immunity,
    Intercept,
    Reflection,
    AreaEffect,
    Deprecated2,
    CreateInventoryItem,
    DamageLimit,
    AreaTeleport,
    Fear,
    Trauma,
    Stealth,
    SeeStealth,
    Flight,
    Disorient,
    Stagger,
    SlowFall,
    Jump,
    SiegeClusterAreaEffect,
    Summon,
    Mount,
    InteractRefusalOverride,
    DeflectAttack,
    NonExistent,
    NoKill,
    NoAggro,
    Dispel,
    Vampire,
    CreateInteractable,
    ModifyCooldown,
    Levitate,
    Pacify,
    ActionList,
    Interrupt,
    Block,
    OffBalance,
    Exhausted,
    ModifyDuration,
    Dodge,
    ShowNon,
    Misdirect,
    FreeCast,
    SiegeCreate,
    SiegeAreaEffect,
    Defend,
    FreeInteract,
    ChangeAppearance,
    AttackerReflect,
    AttackerIntercept,
    Disarm,
    Parry,
    PathLine,
    DoubleFire,
    FireProc,
    Leap,
    Reveal,
    SiegePackUp,
    Recall,
    GrantAbility,
    Hide,
    SetHotbar,
    NoLockPick,
    FillSoulGem,
    SoulGemResurrect,
    DespawnOverride,
    UpdateDeathDialog,
    Deprecated4,
    ClientFx,
    AvoidDeath,
    NonCombatBonus,
    NoSeeTarget,
    Deprecated,
    SetPersonality,
    Basic,
    RewindTime,
    LightHeavyAttackOverride,
    DerivedStatCache,
    AvAReach,
    RandomBranch,
    MountBlock,
    Deprecated3,
    HardDismount,
    LinkTarget,
    CustomTargetArea,
    DamageTransfer,
    DisableItemSets,
    FollowWaypointPath,
    SetAimAtTarget,
    FaceTarget,
    LosMovePosition,
    DisableClientTurning,
    DamageImmune,
    StopMoving,
    ResourceTap,
    HotbarSlotOverride,
    Repair,
    PreventHealing,
    PlayerFlight,
    PauseCooldown,
    DisableGameplayMechanics,
    ModifyStackCount,
}

impl AbilityType {
    pub fn from_id(id: &u8) -> Option<Self> {
        match id {
            0   => Some(Self::None),
            1   => Some(Self::Damage),
            2   => Some(Self::Heal),
            3   => Some(Self::Resurrect),
            4   => Some(Self::Blink),
            5   => Some(Self::Bonus),
            6   => Some(Self::RegisterTrigger),
            7   => Some(Self::SetTarget),
            8   => Some(Self::Threat),
            9   => Some(Self::Stun),
            10  => Some(Self::Snare),
            11  => Some(Self::Silence),
            12  => Some(Self::RemoveType),
            13  => Some(Self::SetCooldown),
            14  => Some(Self::CombatResource),
            15  => Some(Self::DamageShield),
            16  => Some(Self::MovePosition),
            17  => Some(Self::Knockback),
            18  => Some(Self::Charge),
            19  => Some(Self::Immunity),
            20  => Some(Self::Intercept),
            21  => Some(Self::Reflection),
            22  => Some(Self::AreaEffect),
            23  => Some(Self::Deprecated2),
            24  => Some(Self::CreateInventoryItem),
            25  => Some(Self::DamageLimit),
            26  => Some(Self::AreaTeleport),
            27  => Some(Self::Fear),
            28  => Some(Self::Trauma),
            29  => Some(Self::Stealth),
            30  => Some(Self::SeeStealth),
            31  => Some(Self::Flight),
            32  => Some(Self::Disorient),
            33  => Some(Self::Stagger),
            34  => Some(Self::SlowFall),
            35  => Some(Self::Jump),
            36  => Some(Self::SiegeClusterAreaEffect),
            37  => Some(Self::Summon),
            38  => Some(Self::Mount),
            39  => Some(Self::InteractRefusalOverride),
            40  => Some(Self::DeflectAttack),
            41  => Some(Self::NonExistent),
            42  => Some(Self::NoKill),
            43  => Some(Self::NoAggro),
            44  => Some(Self::Dispel),
            45  => Some(Self::Vampire),
            46  => Some(Self::CreateInteractable),
            47  => Some(Self::ModifyCooldown),
            48  => Some(Self::Levitate),
            49  => Some(Self::Pacify),
            50  => Some(Self::ActionList),
            51  => Some(Self::Interrupt),
            52  => Some(Self::Block),
            53  => Some(Self::OffBalance),
            54  => Some(Self::Exhausted),
            55  => Some(Self::ModifyDuration),
            56  => Some(Self::Dodge),
            57  => Some(Self::ShowNon),
            58  => Some(Self::Misdirect),
            59  => Some(Self::FreeCast),
            60  => Some(Self::SiegeCreate),
            61  => Some(Self::SiegeAreaEffect),
            62  => Some(Self::Defend),
            63  => Some(Self::FreeInteract),
            64  => Some(Self::ChangeAppearance),
            65  => Some(Self::AttackerReflect),
            66  => Some(Self::AttackerIntercept),
            67  => Some(Self::Disarm),
            68  => Some(Self::Parry),
            69  => Some(Self::PathLine),
            70  => Some(Self::DoubleFire),
            71  => Some(Self::FireProc),
            72  => Some(Self::Leap),
            73  => Some(Self::Reveal),
            74  => Some(Self::SiegePackUp),
            75  => Some(Self::Recall),
            76  => Some(Self::GrantAbility),
            77  => Some(Self::Hide),
            78  => Some(Self::SetHotbar),
            79  => Some(Self::NoLockPick),
            80  => Some(Self::FillSoulGem),
            81  => Some(Self::SoulGemResurrect),
            82  => Some(Self::DespawnOverride),
            83  => Some(Self::UpdateDeathDialog),
            84  => Some(Self::Deprecated4),
            85  => Some(Self::ClientFx),
            86  => Some(Self::AvoidDeath),
            87  => Some(Self::NonCombatBonus),
            88  => Some(Self::NoSeeTarget),
            89  => Some(Self::Deprecated),
            90  => Some(Self::SetPersonality),
            91  => Some(Self::Basic),
            92  => Some(Self::RewindTime),
            93  => Some(Self::LightHeavyAttackOverride),
            94  => Some(Self::DerivedStatCache),
            95  => Some(Self::AvAReach),
            96  => Some(Self::RandomBranch),
            97  => Some(Self::MountBlock),
            98  => Some(Self::Deprecated3),
            99  => Some(Self::HardDismount),
            100 => Some(Self::LinkTarget),
            101 => Some(Self::CustomTargetArea),
            102 => Some(Self::DamageTransfer),
            103 => Some(Self::DisableItemSets),
            104 => Some(Self::FollowWaypointPath),
            105 => Some(Self::SetAimAtTarget),
            106 => Some(Self::FaceTarget),
            107 => Some(Self::LosMovePosition),
            108 => Some(Self::DisableClientTurning),
            109 => Some(Self::DamageImmune),
            110 => Some(Self::StopMoving),
            111 => Some(Self::ResourceTap),
            112 => Some(Self::HotbarSlotOverride),
            113 => Some(Self::Repair),
            114 => Some(Self::PreventHealing),
            115 => Some(Self::PlayerFlight),
            116 => Some(Self::PauseCooldown),
            117 => Some(Self::DisableGameplayMechanics),
            118 => Some(Self::ModifyStackCount),
            _   => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::None                    => "None",
            Self::Damage                  => "Damage",
            Self::Heal                    => "Heal",
            Self::Resurrect               => "Resurrect",
            Self::Blink                   => "Blink",
            Self::Bonus                   => "Bonus",
            Self::RegisterTrigger         => "Register trigger",
            Self::SetTarget               => "Set target",
            Self::Threat                  => "Threat",
            Self::Stun                    => "Stun",
            Self::Snare                   => "Snare",
            Self::Silence                 => "Silence",
            Self::RemoveType              => "Remove type",
            Self::SetCooldown             => "Set cooldown",
            Self::CombatResource          => "Combat resource",
            Self::DamageShield            => "Damage shield",
            Self::MovePosition            => "Move position",
            Self::Knockback               => "Knockback",
            Self::Charge                  => "Charge",
            Self::Immunity                => "Immunity",
            Self::Intercept               => "Intercept",
            Self::Reflection              => "Reflection",
            Self::AreaEffect              => "Area effect",
            Self::Deprecated2             => "Deprecated 2",
            Self::CreateInventoryItem     => "Create inventory item",
            Self::DamageLimit             => "Damage limit",
            Self::AreaTeleport            => "Area teleport",
            Self::Fear                    => "Fear",
            Self::Trauma                  => "Trauma",
            Self::Stealth                 => "Stealth",
            Self::SeeStealth              => "See stealth",
            Self::Flight                  => "Flight",
            Self::Disorient               => "Disorient",
            Self::Stagger                 => "Stagger",
            Self::SlowFall                => "Slow fall",
            Self::Jump                    => "Jump",
            Self::SiegeClusterAreaEffect  => "Siege cluster area effect",
            Self::Summon                  => "Summon",
            Self::Mount                   => "Mount",
            Self::InteractRefusalOverride => "Interact refusal override",
            Self::DeflectAttack           => "Deflect attack",
            Self::NonExistent             => "Non-existent",
            Self::NoKill                  => "No kill",
            Self::NoAggro                 => "No aggro",
            Self::Dispel                  => "Dispel",
            Self::Vampire                 => "Vampire",
            Self::CreateInteractable      => "Create interactable",
            Self::ModifyCooldown          => "Modify cooldown",
            Self::Levitate                => "Levitate",
            Self::Pacify                  => "Pacify",
            Self::ActionList              => "Action list",
            Self::Interrupt               => "Interrupt",
            Self::Block                   => "Block",
            Self::OffBalance              => "Off balance",
            Self::Exhausted               => "Exhausted",
            Self::ModifyDuration          => "Modify duration",
            Self::Dodge                   => "Dodge",
            Self::ShowNon                 => "Show non",
            Self::Misdirect               => "Misdirect",
            Self::FreeCast                => "Free cast",
            Self::SiegeCreate             => "Siege create",
            Self::SiegeAreaEffect         => "Siege area effect",
            Self::Defend                  => "Defend",
            Self::FreeInteract            => "Free interact",
            Self::ChangeAppearance        => "Change appearance",
            Self::AttackerReflect         => "Attacker reflect",
            Self::AttackerIntercept       => "Attacker intercept",
            Self::Disarm                  => "Disarm",
            Self::Parry                   => "Parry",
            Self::PathLine                => "Path line",
            Self::DoubleFire              => "Double fire",
            Self::FireProc                => "Fire proc",
            Self::Leap                    => "Leap",
            Self::Reveal                  => "Reveal",
            Self::SiegePackUp             => "Siege pack up",
            Self::Recall                  => "Recall",
            Self::GrantAbility            => "Grant ability",
            Self::Hide                    => "Hide",
            Self::SetHotbar               => "Set hotbar",
            Self::NoLockPick              => "No lock pick",
            Self::FillSoulGem             => "Fill soul gem",
            Self::SoulGemResurrect        => "Soul gem resurrect",
            Self::DespawnOverride         => "Despawn override",
            Self::UpdateDeathDialog       => "Update death dialog",
            Self::Deprecated4             => "Deprecated 4",
            Self::ClientFx                => "Client FX",
            Self::AvoidDeath              => "Avoid death",
            Self::NonCombatBonus          => "Non-combat bonus",
            Self::NoSeeTarget             => "No see target",
            Self::Deprecated              => "Deprecated",
            Self::SetPersonality          => "Set personality",
            Self::Basic                   => "Basic",
            Self::RewindTime              => "Rewind time",
            Self::LightHeavyAttackOverride => "Light/Heavy attack override",
            Self::DerivedStatCache        => "Derived stat cache",
            Self::AvAReach                => "AvA reach",
            Self::RandomBranch            => "Random branch",
            Self::MountBlock              => "Mount block",
            Self::Deprecated3             => "Deprecated 3",
            Self::HardDismount            => "Hard dismount",
            Self::LinkTarget              => "Link target",
            Self::CustomTargetArea        => "Custom target area",
            Self::DamageTransfer          => "Damage transfer",
            Self::DisableItemSets         => "Disable item sets",
            Self::FollowWaypointPath      => "Follow waypoint path",
            Self::SetAimAtTarget          => "Set aim at target",
            Self::FaceTarget              => "Face target",
            Self::LosMovePosition         => "LOS move position",
            Self::DisableClientTurning    => "Disable client turning",
            Self::DamageImmune            => "Damage immune",
            Self::StopMoving              => "Stop moving",
            Self::ResourceTap             => "Resource tap",
            Self::HotbarSlotOverride      => "Hotbar slot override",
            Self::Repair                  => "AvA object heal",
            Self::PreventHealing          => "Reduce healing from others",
            Self::PlayerFlight            => "Player flight",
            Self::PauseCooldown           => "Pause cooldown",
            Self::DisableGameplayMechanics => "Disable gameplay mechanics",
            Self::ModifyStackCount        => "Modify stack count",
        }
    }
}

impl fmt::Display for AbilityType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
