use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SkillLine {
    // Weapon
    OneHandAndShield,
    TwoHanded,
    DualWield,
    Bow,
    DestructionStaff,
    RestorationStaff,
    // Armor
    LightArmour,
    MediumArmour,
    HeavyArmour,
    // Templar
    AedricSpear,
    DawnsWrath,
    RestoringLight,
    // Dragonknight
    ArdentFlame,
    DraconicPower,
    EarthenHeart,
    // Nightblade
    Assassination,
    Shadow,
    Siphoning,
    // Sorcerer
    DarkMagic,
    DaedricSummoning,
    StormCalling,
    // Warden
    AnimalCompanions,
    GreenBalance,
    WintersEmbrace,
    // Necromancer
    GraveLord,
    BoneTyrant,
    LivingDeath,
    // Arcanist
    HeraldOfTheTome,
    SoldierOfApocrypha,
    CurativeRuneforms,
    // Guild
    MagesGuild,
    FightersGuild,
    Undaunted,
    PsijicOrder,
    ThievesGuild,
    DarkBrotherhood,
    // Alliance War
    Assault,
    Support,
    Emperor,
    // Racial
    Orc,
    HighElf,
    WoodElf,
    Khajiit,
    Imperial,
    Breton,
    Redguard,
    Argonian,
    DarkElf,
    Nord,
    // World
    Werewolf,
    Vampire,
    SoulMagic,
    Legerdemain,
    Scrying,
    Excavation,
    // Crafting
    Provisioning,
    Alchemy,
    Enchanting,
    Blacksmithing,
    Woodworking,
    Clothing,
    Jewellery,


    // Companion - Bastian
    CompanionArdentWarrior,
    CompanionDraconicArmorBastian,
    CompanionRadiatingHeartBastian,
    // Companion - Mirri
    CompanionDeadlyAssassin,
    CompanionLivingShade,
    CompanionSoulThief,
    // Companion - Weapons & Armor
    CompanionTwoHanded,
    CompanionOneHandAndShield,
    CompanionDualWield,
    CompanionBow,
    CompanionDestructionStaff,
    CompanionRestorationStaff,
    CompanionLightArmor,
    CompanionMediumArmor,
    CompanionHeavyArmor,
    // Companion - Guilds
    CompanionFightersGuild,
    CompanionMagesGuild,
    CompanionUndaunted,
    // Companion - Racial
    CompanionImperial,
    CompanionDarkElf,
    CompanionHighElf,
    CompanionBreton,
    CompanionKhajiitEmber,
    CompanionRedguard,
    CompanionArgonian,
    CompanionKhajiitZerithVar,
    // Companion - Ember
    CompanionLightningCaller,
    CompanionMischievousCaster,
    CompanionPlayfulSchemer,
    // Companion - Isobel
    CompanionBlazingMight,
    CompanionBrilliantShield,
    CompanionHealingGrace,
    // Companion - Sharp
    CompanionBeastsOfTheHunt,
    CompanionWintersBite,
    CompanionVerdantGrowth,
    // Companion - Azandar
    CompanionScholarOfApocrypha,
    CompanionQuillKnight,
    CompanionRevitalizingResearcher,
    // Companion - Zerith-var
    CompanionWarriorsBanishment,
    CompanionRemedyOfAtonement,
    CompanionGuardiansCommitment,
    // Companion - Tanlorin
    CompanionRadiatingHeartTanlorin,
    CompanionDraconicArmorTanlorin,
    CompanionEmpathicFighter,


    // Vengeance
    VengeanceArdentFlame,
    VengeanceDraconicPower,
    VengeanceEarthenHeart,
    VengeanceAssassination,
    VengeanceShadow,
    VengeanceSiphoning,
    VengeanceAedricSpear,
    VengeanceDawnsWrath,
    VengeanceRestoringLight,
    VengeanceDaedricSummoning,
    VengeanceDarkMagic,
    VengeanceStormCalling,
    VengeanceAnimalCompanions,
    VengeanceGreenBalance,
    VengeanceWintersEmbrace,
    VengeanceGraveLord,
    VengeanceBoneTyrant,
    VengeanceLivingDeath,
    VengeanceCurativeRuneforms,
    VengeanceSoldierOfApocrypha,
    VengeanceHeraldOfTheTome,
    VengeanceTwoHanded,
    VengeanceOneHandAndShield,
    VengeanceDualWield,
    VengeanceBow,
    VengeanceDestructionStaff,
    VengeanceRestorationStaff,
    VengeanceAssault,
    VengeanceSupport,
    VengeanceFightersGuild,
    VengeanceMagesGuild,
    VengeanceUndaunted,
    // U50 Vengeance
    VengeanceSoldier,
    VengeanceVanguard,
    VengeanceBattleMedic,
    VengeanceScout,

    // Misc
    PreU49DraconicPower,

    // Class Mastery Passives
    ClassMasteryDragonknight,
    ClassMasteryArcanist,
    ClassMasteryNecromancer,
    ClassMasteryWarden,
    ClassMasteryTemplar,
    ClassMasteryNightblade,
    ClassMasterySorcerer,
}

impl SkillLine {
    pub fn from_id(id: &u32) -> Option<Self> {
        match id {
            29  => Some(Self::OneHandAndShield),
            30  => Some(Self::TwoHanded),
            31  => Some(Self::DualWield),
            32  => Some(Self::Bow),
            33  => Some(Self::DestructionStaff),
            34  => Some(Self::RestorationStaff),
            24  => Some(Self::LightArmour),
            25  => Some(Self::MediumArmour),
            26  => Some(Self::HeavyArmour),
            22  => Some(Self::AedricSpear),
            27  => Some(Self::DawnsWrath),
            28  => Some(Self::RestoringLight),
            35  => Some(Self::ArdentFlame),
            36  => Some(Self::DraconicPower),
            37  => Some(Self::EarthenHeart),
            38  => Some(Self::Assassination),
            39  => Some(Self::Shadow),
            40  => Some(Self::Siphoning),
            41  => Some(Self::DarkMagic),
            42  => Some(Self::DaedricSummoning),
            43  => Some(Self::StormCalling),
            127 => Some(Self::AnimalCompanions),
            128 => Some(Self::GreenBalance),
            129 => Some(Self::WintersEmbrace),
            131 => Some(Self::GraveLord),
            132 => Some(Self::BoneTyrant),
            133 => Some(Self::LivingDeath),
            218 => Some(Self::HeraldOfTheTome),
            219 => Some(Self::SoldierOfApocrypha),
            220 => Some(Self::CurativeRuneforms),
            44  => Some(Self::MagesGuild),
            45  => Some(Self::FightersGuild),
            55  => Some(Self::Undaunted),
            130 => Some(Self::PsijicOrder),
            117 => Some(Self::ThievesGuild),
            118 => Some(Self::DarkBrotherhood),
            48  => Some(Self::Assault),
            67  => Some(Self::Support),
            71  => Some(Self::Emperor),
            52  => Some(Self::Orc),
            56  => Some(Self::HighElf),
            57  => Some(Self::WoodElf),
            58  => Some(Self::Khajiit),
            59  => Some(Self::Imperial),
            60  => Some(Self::Breton),
            62  => Some(Self::Redguard),
            63  => Some(Self::Argonian),
            64  => Some(Self::DarkElf),
            65  => Some(Self::Nord),
            50  => Some(Self::Werewolf),
            51  => Some(Self::Vampire),
            72  => Some(Self::SoulMagic),
            111 => Some(Self::Legerdemain),
            155 => Some(Self::Scrying),
            157 => Some(Self::Excavation),
            76  => Some(Self::Provisioning),
            77  => Some(Self::Alchemy),
            78  => Some(Self::Enchanting),
            79  => Some(Self::Blacksmithing),
            80  => Some(Self::Woodworking),
            81  => Some(Self::Clothing),
            141 => Some(Self::Jewellery),
            174 => Some(Self::CompanionArdentWarrior),
            175 => Some(Self::CompanionDraconicArmorBastian),
            176 => Some(Self::CompanionRadiatingHeartBastian),
            177 => Some(Self::CompanionDeadlyAssassin),
            178 => Some(Self::CompanionLivingShade),
            179 => Some(Self::CompanionSoulThief),
            180 => Some(Self::CompanionTwoHanded),
            181 => Some(Self::CompanionOneHandAndShield),
            182 => Some(Self::CompanionDualWield),
            183 => Some(Self::CompanionBow),
            184 => Some(Self::CompanionDestructionStaff),
            185 => Some(Self::CompanionRestorationStaff),
            186 => Some(Self::CompanionLightArmor),
            187 => Some(Self::CompanionMediumArmor),
            188 => Some(Self::CompanionHeavyArmor),
            189 => Some(Self::CompanionFightersGuild),
            190 => Some(Self::CompanionMagesGuild),
            191 => Some(Self::CompanionUndaunted),
            192 => Some(Self::CompanionImperial),
            193 => Some(Self::CompanionDarkElf),
            267 => Some(Self::CompanionHighElf),
            203 => Some(Self::CompanionBreton),
            199 => Some(Self::CompanionKhajiitEmber),
            249 => Some(Self::CompanionRedguard),
            250 => Some(Self::CompanionArgonian),
            263 => Some(Self::CompanionKhajiitZerithVar),
            196 => Some(Self::CompanionLightningCaller),
            197 => Some(Self::CompanionMischievousCaster),
            198 => Some(Self::CompanionPlayfulSchemer),
            200 => Some(Self::CompanionBlazingMight),
            201 => Some(Self::CompanionBrilliantShield),
            202 => Some(Self::CompanionHealingGrace),
            241 => Some(Self::CompanionBeastsOfTheHunt),
            242 => Some(Self::CompanionWintersBite),
            243 => Some(Self::CompanionVerdantGrowth),
            246 => Some(Self::CompanionScholarOfApocrypha),
            247 => Some(Self::CompanionQuillKnight),
            248 => Some(Self::CompanionRevitalizingResearcher),
            260 => Some(Self::CompanionWarriorsBanishment),
            261 => Some(Self::CompanionRemedyOfAtonement),
            262 => Some(Self::CompanionGuardiansCommitment),
            264 => Some(Self::CompanionRadiatingHeartTanlorin),
            265 => Some(Self::CompanionDraconicArmorTanlorin),
            266 => Some(Self::CompanionEmpathicFighter),
            297 => Some(Self::VengeanceArdentFlame),
            298 => Some(Self::VengeanceDraconicPower),
            299 => Some(Self::VengeanceEarthenHeart),
            300 => Some(Self::VengeanceAssassination),
            301 => Some(Self::VengeanceShadow),
            302 => Some(Self::VengeanceSiphoning),
            303 => Some(Self::VengeanceAedricSpear),
            304 => Some(Self::VengeanceDawnsWrath),
            305 => Some(Self::VengeanceRestoringLight),
            306 => Some(Self::VengeanceDaedricSummoning),
            307 => Some(Self::VengeanceDarkMagic),
            308 => Some(Self::VengeanceStormCalling),
            309 => Some(Self::VengeanceAnimalCompanions),
            310 => Some(Self::VengeanceGreenBalance),
            311 => Some(Self::VengeanceWintersEmbrace),
            312 => Some(Self::VengeanceGraveLord),
            313 => Some(Self::VengeanceBoneTyrant),
            314 => Some(Self::VengeanceLivingDeath),
            315 => Some(Self::VengeanceCurativeRuneforms),
            316 => Some(Self::VengeanceSoldierOfApocrypha),
            317 => Some(Self::VengeanceHeraldOfTheTome),
            319 => Some(Self::VengeanceTwoHanded),
            320 => Some(Self::VengeanceOneHandAndShield),
            321 => Some(Self::VengeanceDualWield),
            322 => Some(Self::VengeanceBow),
            323 => Some(Self::VengeanceDestructionStaff),
            324 => Some(Self::VengeanceRestorationStaff),
            325 => Some(Self::VengeanceAssault),
            326 => Some(Self::VengeanceSupport),
            330 => Some(Self::VengeanceFightersGuild),
            331 => Some(Self::VengeanceMagesGuild),
            332 => Some(Self::VengeanceUndaunted),
            334 => Some(Self::PreU49DraconicPower),
            339 => Some(Self::VengeanceSoldier),
            340 => Some(Self::VengeanceVanguard),
            341 => Some(Self::VengeanceBattleMedic),
            342 => Some(Self::VengeanceScout),
            351 => Some(Self::ClassMasteryDragonknight),
            352 => Some(Self::ClassMasteryArcanist),
            353 => Some(Self::ClassMasteryNecromancer),
            354 => Some(Self::ClassMasteryWarden),
            355 => Some(Self::ClassMasteryTemplar),
            356 => Some(Self::ClassMasteryNightblade),
            357 => Some(Self::ClassMasterySorcerer),
            _   => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::OneHandAndShield               => "One Hand and Shield",
            Self::TwoHanded                      => "Two Handed",
            Self::DualWield                      => "Dual Wield",
            Self::Bow                            => "Bow",
            Self::DestructionStaff               => "Destruction Staff",
            Self::RestorationStaff               => "Restoration Staff",
            Self::LightArmour                    => "Light Armour",
            Self::MediumArmour                   => "Medium Armour",
            Self::HeavyArmour                    => "Heavy Armour",
            Self::AedricSpear                    => "Aedric Spear",
            Self::DawnsWrath                     => "Dawn's Wrath",
            Self::RestoringLight                 => "Restoring Light",
            Self::ArdentFlame                    => "Ardent Flame",
            Self::DraconicPower                  => "Draconic Power",
            Self::EarthenHeart                   => "Earthen Heart",
            Self::Assassination                  => "Assassination",
            Self::Shadow                         => "Shadow",
            Self::Siphoning                      => "Siphoning",
            Self::DarkMagic                      => "Dark Magic",
            Self::DaedricSummoning               => "Daedric Summoning",
            Self::StormCalling                   => "Storm Calling",
            Self::AnimalCompanions               => "Animal Companions",
            Self::GreenBalance                   => "Green Balance",
            Self::WintersEmbrace                 => "Winter's Embrace",
            Self::GraveLord                      => "Grave Lord",
            Self::BoneTyrant                     => "Bone Tyrant",
            Self::LivingDeath                    => "Living Death",
            Self::HeraldOfTheTome                => "Herald of the Tome",
            Self::SoldierOfApocrypha             => "Soldier of Apocrypha",
            Self::CurativeRuneforms              => "Curative Runeforms",
            Self::MagesGuild                     => "Mages Guild",
            Self::FightersGuild                  => "Fighters Guild",
            Self::Undaunted                      => "Undaunted",
            Self::PsijicOrder                    => "Psijic Order",
            Self::ThievesGuild                   => "Thieves Guild",
            Self::DarkBrotherhood                => "Dark Brotherhood",
            Self::Assault                        => "Assault",
            Self::Support                        => "Support",
            Self::Emperor                        => "Emperor",
            Self::Orc                            => "Orc",
            Self::HighElf                        => "High Elf",
            Self::WoodElf                        => "Wood Elf",
            Self::Khajiit                        => "Khajiit",
            Self::Imperial                       => "Imperial",
            Self::Breton                         => "Breton",
            Self::Redguard                       => "Redguard",
            Self::Argonian                       => "Argonian",
            Self::DarkElf                        => "Dark Elf",
            Self::Nord                           => "Nord",
            Self::Werewolf                       => "Werewolf",
            Self::Vampire                        => "Vampire",
            Self::SoulMagic                      => "Soul Magic",
            Self::Legerdemain                    => "Legerdemain",
            Self::Scrying                        => "Scrying",
            Self::Excavation                     => "Excavation",
            Self::Provisioning                   => "Provisioning",
            Self::Alchemy                        => "Alchemy",
            Self::Enchanting                     => "Enchanting",
            Self::Blacksmithing                  => "Blacksmithing",
            Self::Woodworking                    => "Woodworking",
            Self::Clothing                       => "Clothing",
            Self::Jewellery                      => "Jewellery",
            Self::CompanionArdentWarrior         => "Companion Ardent Warrior",
            Self::CompanionDraconicArmorBastian  => "Companion Draconic Armor (Bastian)",
            Self::CompanionRadiatingHeartBastian => "Companion Radiating Heart (Bastian)",
            Self::CompanionDeadlyAssassin        => "Companion Deadly Assassin",
            Self::CompanionLivingShade           => "Companion Living Shade",
            Self::CompanionSoulThief             => "Companion Soul Thief",
            Self::CompanionTwoHanded             => "Companion Two Handed",
            Self::CompanionOneHandAndShield      => "Companion One Hand and Shield",
            Self::CompanionDualWield             => "Companion Dual Wield",
            Self::CompanionBow                   => "Companion Bow",
            Self::CompanionDestructionStaff      => "Companion Destruction Staff",
            Self::CompanionRestorationStaff      => "Companion Restoration Staff",
            Self::CompanionLightArmor            => "Companion Light Armor",
            Self::CompanionMediumArmor           => "Companion Medium Armor",
            Self::CompanionHeavyArmor            => "Companion Heavy Armor",
            Self::CompanionFightersGuild         => "Companion Fighters Guild",
            Self::CompanionMagesGuild            => "Companion Mages Guild",
            Self::CompanionUndaunted             => "Companion Undaunted",
            Self::CompanionImperial              => "Companion Imperial",
            Self::CompanionDarkElf               => "Companion Dark Elf",
            Self::CompanionHighElf               => "Companion High Elf",
            Self::CompanionBreton                => "Companion Breton",
            Self::CompanionKhajiitEmber          => "Companion Khajiit (Ember)",
            Self::CompanionRedguard              => "Companion Redguard",
            Self::CompanionArgonian              => "Companion Argonian",
            Self::CompanionKhajiitZerithVar      => "Companion Khajiit (Zerith-var)",
            Self::CompanionLightningCaller       => "Companion Lightning Caller",
            Self::CompanionMischievousCaster     => "Companion Mischievous Caster",
            Self::CompanionPlayfulSchemer        => "Companion Playful Schemer",
            Self::CompanionBlazingMight          => "Companion Blazing Might",
            Self::CompanionBrilliantShield       => "Companion Brilliant Shield",
            Self::CompanionHealingGrace          => "Companion Healing Grace",
            Self::CompanionBeastsOfTheHunt       => "Companion Beasts of the Hunt",
            Self::CompanionWintersBite           => "Companion Winter's Bite",
            Self::CompanionVerdantGrowth         => "Companion Verdant Growth",
            Self::CompanionScholarOfApocrypha    => "Companion Scholar of Apocrypha",
            Self::CompanionQuillKnight           => "Companion Quill Knight",
            Self::CompanionRevitalizingResearcher => "Companion Revitalizing Researcher",
            Self::CompanionWarriorsBanishment    => "Companion Warrior's Banishment",
            Self::CompanionRemedyOfAtonement     => "Companion Remedy of Atonement",
            Self::CompanionGuardiansCommitment   => "Companion Guardian's Commitment",
            Self::CompanionRadiatingHeartTanlorin => "Companion Radiating Heart (Tanlorin)",
            Self::CompanionDraconicArmorTanlorin => "Companion Draconic Armor (Tanlorin)",
            Self::CompanionEmpathicFighter       => "Companion Empathic Fighter",
            Self::VengeanceArdentFlame           => "Vengeance Ardent Flame",
            Self::VengeanceDraconicPower         => "Vengeance Draconic Power",
            Self::VengeanceEarthenHeart          => "Vengeance Earthen Heart",
            Self::VengeanceAssassination         => "Vengeance Assassination",
            Self::VengeanceShadow                => "Vengeance Shadow",
            Self::VengeanceSiphoning             => "Vengeance Siphoning",
            Self::VengeanceAedricSpear           => "Vengeance Aedric Spear",
            Self::VengeanceDawnsWrath            => "Vengeance Dawn's Wrath",
            Self::VengeanceRestoringLight        => "Vengeance Restoring Light",
            Self::VengeanceDaedricSummoning      => "Vengeance Daedric Summoning",
            Self::VengeanceDarkMagic             => "Vengeance Dark Magic",
            Self::VengeanceStormCalling          => "Vengeance Storm Calling",
            Self::VengeanceAnimalCompanions      => "Vengeance Animal Companions",
            Self::VengeanceGreenBalance          => "Vengeance Green Balance",
            Self::VengeanceWintersEmbrace        => "Vengeance Winter's Embrace",
            Self::VengeanceGraveLord             => "Vengeance Grave Lord",
            Self::VengeanceBoneTyrant            => "Vengeance Bone Tyrant",
            Self::VengeanceLivingDeath           => "Vengeance Living Death",
            Self::VengeanceCurativeRuneforms     => "Vengeance Curative Runeforms",
            Self::VengeanceSoldierOfApocrypha    => "Vengeance Soldier of Apocrypha",
            Self::VengeanceHeraldOfTheTome       => "Vengeance Herald of the Tome",
            Self::VengeanceTwoHanded             => "Vengeance Two Handed",
            Self::VengeanceOneHandAndShield      => "Vengeance One Hand and Shield",
            Self::VengeanceDualWield             => "Vengeance Dual Wield",
            Self::VengeanceBow                   => "Vengeance Bow",
            Self::VengeanceDestructionStaff      => "Vengeance Destruction Staff",
            Self::VengeanceRestorationStaff      => "Vengeance Restoration Staff",
            Self::VengeanceAssault               => "Vengeance Assault",
            Self::VengeanceSupport               => "Vengeance Support",
            Self::VengeanceFightersGuild         => "Vengeance Fighters Guild",
            Self::VengeanceMagesGuild            => "Vengeance Mages Guild",
            Self::VengeanceUndaunted             => "Vengeance Undaunted",
            Self::VengeanceSoldier               => "Vengeance Soldier",
            Self::VengeanceVanguard              => "Vengeance Vanguard",
            Self::VengeanceBattleMedic           => "Vengeance Battle Medic",
            Self::VengeanceScout                 => "Vengeance Scout",
            Self::PreU49DraconicPower            => "Pre-U49 Draconic Power",
            Self::ClassMasteryDragonknight       => "Dragonknight Class Mastery",
            Self::ClassMasteryArcanist           => "Arcanist Class Mastery",
            Self::ClassMasteryNecromancer        => "Necromancer Class Mastery",
            Self::ClassMasteryWarden             => "Warden Class Mastery",
            Self::ClassMasteryTemplar            => "Templar Class Mastery",
            Self::ClassMasteryNightblade         => "Nightblade Class Mastery",
            Self::ClassMasterySorcerer           => "Sorcerer Class Mastery",
        }
    }

    pub fn is_vengeance(&self) -> bool {
        matches!(self, Self::VengeanceArdentFlame | Self::VengeanceDraconicPower | Self::VengeanceEarthenHeart | Self::VengeanceAssassination | Self::VengeanceShadow | Self::VengeanceSiphoning | Self::VengeanceAedricSpear | Self::VengeanceDawnsWrath | Self::VengeanceRestoringLight | Self::VengeanceDaedricSummoning | Self::VengeanceDarkMagic | Self::VengeanceStormCalling | Self::VengeanceAnimalCompanions | Self::VengeanceGreenBalance | Self::VengeanceWintersEmbrace | Self::VengeanceGraveLord | Self::VengeanceBoneTyrant | Self::VengeanceLivingDeath | Self::VengeanceCurativeRuneforms | Self::VengeanceSoldierOfApocrypha | Self::VengeanceHeraldOfTheTome | Self::VengeanceTwoHanded | Self::VengeanceOneHandAndShield | Self::VengeanceDualWield | Self::VengeanceBow | Self::VengeanceDestructionStaff | Self::VengeanceRestorationStaff | Self::VengeanceAssault | Self::VengeanceSupport | Self::VengeanceFightersGuild | Self::VengeanceMagesGuild | Self::VengeanceUndaunted | Self::VengeanceSoldier | Self::VengeanceVanguard | Self::VengeanceBattleMedic | Self::VengeanceScout)
    }

    pub fn is_companion(&self) -> bool {
        matches!(self, Self::CompanionArdentWarrior | Self::CompanionDraconicArmorBastian | Self::CompanionRadiatingHeartBastian |Self::CompanionDeadlyAssassin | Self::CompanionLivingShade | Self::CompanionSoulThief |Self::CompanionTwoHanded | Self::CompanionOneHandAndShield | Self::CompanionDualWield | Self::CompanionBow | Self::CompanionDestructionStaff | Self::CompanionRestorationStaff | Self::CompanionLightArmor | Self::CompanionMediumArmor | Self::CompanionHeavyArmor |Self::CompanionFightersGuild | Self::CompanionMagesGuild | Self::CompanionUndaunted |Self::CompanionImperial | Self::CompanionDarkElf | Self::CompanionHighElf | Self::CompanionBreton | Self::CompanionKhajiitEmber | Self::CompanionRedguard | Self::CompanionArgonian | Self::CompanionKhajiitZerithVar |Self::CompanionLightningCaller | Self::CompanionMischievousCaster | Self::CompanionPlayfulSchemer |Self::CompanionBlazingMight | Self::CompanionBrilliantShield | Self::CompanionHealingGrace |Self::CompanionBeastsOfTheHunt | Self::CompanionWintersBite | Self::CompanionVerdantGrowth |Self::CompanionScholarOfApocrypha | Self::CompanionQuillKnight | Self::CompanionRevitalizingResearcher |Self::CompanionWarriorsBanishment | Self::CompanionRemedyOfAtonement | Self::CompanionGuardiansCommitment |Self::CompanionRadiatingHeartTanlorin | Self::CompanionDraconicArmorTanlorin | Self::CompanionEmpathicFighter)
    }

    pub fn is_class_mastery(&self) -> bool {
        matches!(self, Self::ClassMasteryDragonknight | Self::ClassMasteryArcanist | Self::ClassMasteryNecromancer | Self::ClassMasteryWarden | Self::ClassMasteryTemplar | Self::ClassMasteryNightblade | Self::ClassMasterySorcerer)
    }
}

impl fmt::Display for SkillLine {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
