use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TooltipType {
    ConditionalBuffActive,
    BuffGain,
    ActivationEffect,
    ResourceGain,
    MartialDamage,
    MagicalDamage,
    TickRate,
    Duration,
    DeprecatedChampionPoints,
    DeprecatedChampionPoints2,
    IncreasedDurationVsMonsters,
    MinimumCooldown,
    DeprecatedZeroDuration,
    SingleTargetDoT,
    DeprecatedMultiHit,
    SingleTargetHeal,
    AreaHoT,
    Percentage,
    IncreaseDurationOf,
    DeprecatedHalfSecondDuration,
    ReduceCostIncreaseRecovery,
    DeprecatedTriResourceGrant,
    DeprecatedArmourPercent,
    DeprecatedArmourMs,
    SelfHeal,
    Knockback,
    DeprecatedIncreasedChance,
    DelayedStrike,
    StatPercentage,
    ReduceHeatPercent,
    FlatConstant,
    PercentageConstant,
    ThresholdBelowHealthPercent,
    BonusUpToPercent,
    CompanionEffect,
    BuffExplanationText,
    BuffExplanationText2,
    MajorMinorBuffGain,
}

impl TooltipType {
    pub fn from_id(id: &u32) -> Option<Self> {
        match id {
            3   => Some(Self::ConditionalBuffActive),
            8   => Some(Self::BuffGain),
            10  => Some(Self::ActivationEffect),
            16  => Some(Self::ResourceGain),
            17  => Some(Self::MartialDamage),
            18  => Some(Self::MagicalDamage),
            19  => Some(Self::TickRate),
            20  => Some(Self::Duration),
            21  => Some(Self::DeprecatedChampionPoints),
            22  => Some(Self::DeprecatedChampionPoints2),
            31  => Some(Self::IncreasedDurationVsMonsters),
            44  => Some(Self::MinimumCooldown),
            48  => Some(Self::DeprecatedZeroDuration),
            49  => Some(Self::SingleTargetDoT),
            51  => Some(Self::DeprecatedMultiHit),
            52  => Some(Self::SingleTargetHeal),
            53  => Some(Self::AreaHoT),
            55  => Some(Self::Percentage),
            56  => Some(Self::IncreaseDurationOf),
            57  => Some(Self::DeprecatedHalfSecondDuration),
            58  => Some(Self::ReduceCostIncreaseRecovery),
            72  => Some(Self::DeprecatedTriResourceGrant),
            73  => Some(Self::DeprecatedArmourPercent),
            79  => Some(Self::DeprecatedArmourMs),
            90  => Some(Self::SelfHeal),
            91  => Some(Self::Knockback),
            92  => Some(Self::DeprecatedIncreasedChance),
            93  => Some(Self::DelayedStrike),
            96  => Some(Self::StatPercentage),
            97  => Some(Self::ReduceHeatPercent),
            99  => Some(Self::FlatConstant),
            100 => Some(Self::PercentageConstant),
            104 => Some(Self::ThresholdBelowHealthPercent),
            105 => Some(Self::BonusUpToPercent),
            114 => Some(Self::CompanionEffect),
            121 => Some(Self::BuffExplanationText),
            122 => Some(Self::BuffExplanationText2),
            123 => Some(Self::MajorMinorBuffGain),
            _   => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::ConditionalBuffActive       => "ConditionalBuffActive",
            Self::BuffGain                    => "BuffGain",
            Self::ActivationEffect            => "ActivationEffect",
            Self::ResourceGain                => "ResourceGain",
            Self::MartialDamage               => "MartialDamage",
            Self::MagicalDamage               => "MagicalDamage",
            Self::TickRate                    => "TickRate",
            Self::Duration                    => "Duration",
            Self::DeprecatedChampionPoints    => "DeprecatedChampionPoints",
            Self::DeprecatedChampionPoints2   => "DeprecatedChampionPoints2",
            Self::IncreasedDurationVsMonsters => "IncreasedDurationVsMonsters",
            Self::MinimumCooldown             => "MinimumCooldown",
            Self::DeprecatedZeroDuration      => "DeprecatedZeroDuration",
            Self::SingleTargetDoT             => "SingleTargetDoT",
            Self::DeprecatedMultiHit          => "DeprecatedMultiHit",
            Self::SingleTargetHeal            => "SingleTargetHeal",
            Self::AreaHoT                     => "AreaHoT",
            Self::Percentage                  => "Percentage",
            Self::IncreaseDurationOf          => "IncreaseDurationOf",
            Self::DeprecatedHalfSecondDuration => "DeprecatedHalfSecondDuration",
            Self::ReduceCostIncreaseRecovery  => "ReduceCostIncreaseRecovery",
            Self::DeprecatedTriResourceGrant  => "DeprecatedTriResourceGrant",
            Self::DeprecatedArmourPercent     => "DeprecatedArmourPercent",
            Self::DeprecatedArmourMs          => "DeprecatedArmourMs",
            Self::SelfHeal                    => "SelfHeal",
            Self::Knockback                   => "Knockback",
            Self::DeprecatedIncreasedChance   => "DeprecatedIncreasedChance",
            Self::DelayedStrike               => "DelayedStrike",
            Self::StatPercentage              => "StatPercentage",
            Self::ReduceHeatPercent           => "ReduceHeatPercent",
            Self::FlatConstant                => "FlatConstant",
            Self::PercentageConstant          => "PercentageConstant",
            Self::ThresholdBelowHealthPercent => "ThresholdBelowHealthPercent",
            Self::BonusUpToPercent            => "BonusUpToPercent",
            Self::CompanionEffect             => "CompanionEffect",
            Self::BuffExplanationText         => "BuffExplanationText",
            Self::BuffExplanationText2        => "BuffExplanationText2",
            Self::MajorMinorBuffGain          => "MajorMinorBuffGain",
        }
    }
}

impl fmt::Display for TooltipType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
