use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DamageType {
    Generic,
    Physical,
    Flame,
    Shock,
    Oblivion,
    Frost,
    Earth,
    Magic,
    Drown,
    Disease,
    Poison,
    Bleed,
}

impl DamageType {
    pub fn from_id(id: &u16) -> Option<Self> {
        match id {
            1  => Some(Self::Generic),
            2  => Some(Self::Physical),
            3  => Some(Self::Flame),
            4  => Some(Self::Shock),
            5  => Some(Self::Oblivion),
            6  => Some(Self::Frost),
            7  => Some(Self::Earth),
            8  => Some(Self::Magic),
            9  => Some(Self::Drown),
            10 => Some(Self::Disease),
            11 => Some(Self::Poison),
            12 => Some(Self::Bleed),
            _  => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Generic  => "Generic",
            Self::Physical => "Physical",
            Self::Flame    => "Flame",
            Self::Shock    => "Shock",
            Self::Oblivion => "Oblivion",
            Self::Frost    => "Frost",
            Self::Earth    => "Earth",
            Self::Magic    => "Magic",
            Self::Drown    => "Drown",
            Self::Disease  => "Disease",
            Self::Poison   => "Poison",
            Self::Bleed    => "Bleed",
        }
    }
}

impl fmt::Display for DamageType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Mechanic {
    None,
    Magicka,
    Stamina,
    EqualMagickaAndStamina,
    Ultimate,
    Health,
    EqualHealthAndMagicka,
}

impl Mechanic {
    pub fn from_id(id: &u8) -> Option<Self> {
        match id {
            0  => Some(Self::None),
            1  => Some(Self::Magicka),
            4  => Some(Self::Stamina),
            5  => Some(Self::EqualMagickaAndStamina),
            8  => Some(Self::Ultimate),
            32 => Some(Self::Health),
            33 => Some(Self::EqualHealthAndMagicka),
            _  => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::None                  => "None",
            Self::Magicka               => "Magicka",
            Self::Stamina               => "Stamina",
            Self::EqualMagickaAndStamina => "Equal Magicka and Stamina",
            Self::Ultimate              => "Ultimate",
            Self::Health                => "Health",
            Self::EqualHealthAndMagicka => "Equal Health and Magicka",
        }
    }
}

impl fmt::Display for Mechanic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CoefficientType {
    MaximumMagicka,
    MaximumHealth,
    HealthRecovery,
    SpellResistance,
    PhysicalResistance,
    SpellDamage,
    MaximumStamina,
    WeaponDamage,
}

impl CoefficientType {
    pub fn from_id(id: &u8) -> Option<Self> {
        match id {
            4  => Some(Self::MaximumMagicka),
            7  => Some(Self::MaximumHealth),
            8  => Some(Self::HealthRecovery),
            13 => Some(Self::SpellResistance),
            22 => Some(Self::PhysicalResistance),
            25 => Some(Self::SpellDamage),
            29 => Some(Self::MaximumStamina),
            35 => Some(Self::WeaponDamage),
            _  => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::MaximumMagicka      => "Maximum Magicka",
            Self::MaximumHealth       => "Maximum Health",
            Self::HealthRecovery      => "Health Recovery",
            Self::SpellResistance     => "Spell Resistance",
            Self::PhysicalResistance  => "Physical Resistance",
            Self::SpellDamage         => "Spell Damage",
            Self::MaximumStamina      => "Maximum Stamina",
            Self::WeaponDamage        => "Weapon Damage",
        }
    }
}

impl fmt::Display for CoefficientType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AbilityType {
    None,
    Damage,
    Heal,
    Resurrect,
    Blink,
    Bonus,
    RegisterTrigger,
    SetTarget,
    Threat,
    Stun,
    Snare,
    Silence,
    RemoveType,
    SetCooldown,
    CombatResource,
    DamageShield,
    MovePosition,
    Knockback,
    Charge,
    Immunity,
    Intercept,
    Reflection,
    AreaEffect,
    Deprecated2,
    CreateInventoryItem,
    DamageLimit,
    AreaTeleport,
    Fear,
    Trauma,
    Stealth,
    SeeStealth,
    Flight,
    Disorient,
    Stagger,
    SlowFall,
    Jump,
    SiegeClusterAreaEffect,
    Summon,
    Mount,
    InteractRefusalOverride,
    DeflectAttack,
    NonExistent,
    NoKill,
    NoAggro,
    Dispel,
    Vampire,
    CreateInteractable,
    ModifyCooldown,
    Levitate,
    Pacify,
    ActionList,
    Interrupt,
    Block,
    OffBalance,
    Exhausted,
    ModifyDuration,
    Dodge,
    ShowNon,
    Misdirect,
    FreeCast,
    SiegeCreate,
    SiegeAreaEffect,
    Defend,
    FreeInteract,
    ChangeAppearance,
    AttackerReflect,
    AttackerIntercept,
    Disarm,
    Parry,
    PathLine,
    DoubleFire,
    FireProc,
    Leap,
    Reveal,
    SiegePackUp,
    Recall,
    GrantAbility,
    Hide,
    SetHotbar,
    NoLockPick,
    FillSoulGem,
    SoulGemResurrect,
    DespawnOverride,
    UpdateDeathDialog,
    Deprecated4,
    ClientFx,
    AvoidDeath,
    NonCombatBonus,
    NoSeeTarget,
    Deprecated,
    SetPersonality,
    Basic,
    RewindTime,
    LightHeavyAttackOverride,
    DerivedStatCache,
    AvAReach,
    RandomBranch,
    MountBlock,
    Deprecated3,
    HardDismount,
    LinkTarget,
    CustomTargetArea,
    DamageTransfer,
    DisableItemSets,
    FollowWaypointPath,
    SetAimAtTarget,
    FaceTarget,
    LosMovePosition,
    DisableClientTurning,
    DamageImmune,
    StopMoving,
    ResourceTap,
    ShareUltimate,
    AvAObjectHeal,
    ReduceHealingFromOthers,
    ReduceGravity,
    NightMarketUnknown,
    MandatorySnare,
}

impl AbilityType {
    pub fn from_id(id: &u8) -> Option<Self> {
        match id {
            0   => Some(Self::None),
            1   => Some(Self::Damage),
            2   => Some(Self::Heal),
            3   => Some(Self::Resurrect),
            4   => Some(Self::Blink),
            5   => Some(Self::Bonus),
            6   => Some(Self::RegisterTrigger),
            7   => Some(Self::SetTarget),
            8   => Some(Self::Threat),
            9   => Some(Self::Stun),
            10  => Some(Self::Snare),
            11  => Some(Self::Silence),
            12  => Some(Self::RemoveType),
            13  => Some(Self::SetCooldown),
            14  => Some(Self::CombatResource),
            15  => Some(Self::DamageShield),
            16  => Some(Self::MovePosition),
            17  => Some(Self::Knockback),
            18  => Some(Self::Charge),
            19  => Some(Self::Immunity),
            20  => Some(Self::Intercept),
            21  => Some(Self::Reflection),
            22  => Some(Self::AreaEffect),
            23  => Some(Self::Deprecated2),
            24  => Some(Self::CreateInventoryItem),
            25  => Some(Self::DamageLimit),
            26  => Some(Self::AreaTeleport),
            27  => Some(Self::Fear),
            28  => Some(Self::Trauma),
            29  => Some(Self::Stealth),
            30  => Some(Self::SeeStealth),
            31  => Some(Self::Flight),
            32  => Some(Self::Disorient),
            33  => Some(Self::Stagger),
            34  => Some(Self::SlowFall),
            35  => Some(Self::Jump),
            36  => Some(Self::SiegeClusterAreaEffect),
            37  => Some(Self::Summon),
            38  => Some(Self::Mount),
            39  => Some(Self::InteractRefusalOverride),
            40  => Some(Self::DeflectAttack),
            41  => Some(Self::NonExistent),
            42  => Some(Self::NoKill),
            43  => Some(Self::NoAggro),
            44  => Some(Self::Dispel),
            45  => Some(Self::Vampire),
            46  => Some(Self::CreateInteractable),
            47  => Some(Self::ModifyCooldown),
            48  => Some(Self::Levitate),
            49  => Some(Self::Pacify),
            50  => Some(Self::ActionList),
            51  => Some(Self::Interrupt),
            52  => Some(Self::Block),
            53  => Some(Self::OffBalance),
            54  => Some(Self::Exhausted),
            55  => Some(Self::ModifyDuration),
            56  => Some(Self::Dodge),
            57  => Some(Self::ShowNon),
            58  => Some(Self::Misdirect),
            59  => Some(Self::FreeCast),
            60  => Some(Self::SiegeCreate),
            61  => Some(Self::SiegeAreaEffect),
            62  => Some(Self::Defend),
            63  => Some(Self::FreeInteract),
            64  => Some(Self::ChangeAppearance),
            65  => Some(Self::AttackerReflect),
            66  => Some(Self::AttackerIntercept),
            67  => Some(Self::Disarm),
            68  => Some(Self::Parry),
            69  => Some(Self::PathLine),
            70  => Some(Self::DoubleFire),
            71  => Some(Self::FireProc),
            72  => Some(Self::Leap),
            73  => Some(Self::Reveal),
            74  => Some(Self::SiegePackUp),
            75  => Some(Self::Recall),
            76  => Some(Self::GrantAbility),
            77  => Some(Self::Hide),
            78  => Some(Self::SetHotbar),
            79  => Some(Self::NoLockPick),
            80  => Some(Self::FillSoulGem),
            81  => Some(Self::SoulGemResurrect),
            82  => Some(Self::DespawnOverride),
            83  => Some(Self::UpdateDeathDialog),
            84  => Some(Self::Deprecated4),
            85  => Some(Self::ClientFx),
            86  => Some(Self::AvoidDeath),
            87  => Some(Self::NonCombatBonus),
            88  => Some(Self::NoSeeTarget),
            89  => Some(Self::Deprecated),
            90  => Some(Self::SetPersonality),
            91  => Some(Self::Basic),
            92  => Some(Self::RewindTime),
            93  => Some(Self::LightHeavyAttackOverride),
            94  => Some(Self::DerivedStatCache),
            95  => Some(Self::AvAReach),
            96  => Some(Self::RandomBranch),
            97  => Some(Self::MountBlock),
            98  => Some(Self::Deprecated3),
            99  => Some(Self::HardDismount),
            100 => Some(Self::LinkTarget),
            101 => Some(Self::CustomTargetArea),
            102 => Some(Self::DamageTransfer),
            103 => Some(Self::DisableItemSets),
            104 => Some(Self::FollowWaypointPath),
            105 => Some(Self::SetAimAtTarget),
            106 => Some(Self::FaceTarget),
            107 => Some(Self::LosMovePosition),
            108 => Some(Self::DisableClientTurning),
            109 => Some(Self::DamageImmune),
            110 => Some(Self::StopMoving),
            111 => Some(Self::ResourceTap),
            112 => Some(Self::ShareUltimate),
            113 => Some(Self::AvAObjectHeal),
            114 => Some(Self::ReduceHealingFromOthers),
            115 => Some(Self::ReduceGravity),
            116 => Some(Self::NightMarketUnknown),
            117 => Some(Self::MandatorySnare),
            _   => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::None                    => "None",
            Self::Damage                  => "Damage",
            Self::Heal                    => "Heal",
            Self::Resurrect               => "Resurrect",
            Self::Blink                   => "Blink",
            Self::Bonus                   => "Bonus",
            Self::RegisterTrigger         => "Register trigger",
            Self::SetTarget               => "Set target",
            Self::Threat                  => "Threat",
            Self::Stun                    => "Stun",
            Self::Snare                   => "Snare",
            Self::Silence                 => "Silence",
            Self::RemoveType              => "Remove type",
            Self::SetCooldown             => "Set cooldown",
            Self::CombatResource          => "Combat resource",
            Self::DamageShield            => "Damage shield",
            Self::MovePosition            => "Move position",
            Self::Knockback               => "Knockback",
            Self::Charge                  => "Charge",
            Self::Immunity                => "Immunity",
            Self::Intercept               => "Intercept",
            Self::Reflection              => "Reflection",
            Self::AreaEffect              => "Area effect",
            Self::Deprecated2             => "Deprecated 2",
            Self::CreateInventoryItem     => "Create inventory item",
            Self::DamageLimit             => "Damage limit",
            Self::AreaTeleport            => "Area teleport",
            Self::Fear                    => "Fear",
            Self::Trauma                  => "Trauma",
            Self::Stealth                 => "Stealth",
            Self::SeeStealth              => "See stealth",
            Self::Flight                  => "Flight",
            Self::Disorient               => "Disorient",
            Self::Stagger                 => "Stagger",
            Self::SlowFall                => "Slow fall",
            Self::Jump                    => "Jump",
            Self::SiegeClusterAreaEffect  => "Siege cluster area effect",
            Self::Summon                  => "Summon",
            Self::Mount                   => "Mount",
            Self::InteractRefusalOverride => "Interact refusal override",
            Self::DeflectAttack           => "Deflect attack",
            Self::NonExistent             => "Non-existent",
            Self::NoKill                  => "No kill",
            Self::NoAggro                 => "No aggro",
            Self::Dispel                  => "Dispel",
            Self::Vampire                 => "Vampire",
            Self::CreateInteractable      => "Create interactable",
            Self::ModifyCooldown          => "Modify cooldown",
            Self::Levitate                => "Levitate",
            Self::Pacify                  => "Pacify",
            Self::ActionList              => "Action list",
            Self::Interrupt               => "Interrupt",
            Self::Block                   => "Block",
            Self::OffBalance              => "Off balance",
            Self::Exhausted               => "Exhausted",
            Self::ModifyDuration          => "Modify duration",
            Self::Dodge                   => "Dodge",
            Self::ShowNon                 => "Show non",
            Self::Misdirect               => "Misdirect",
            Self::FreeCast                => "Free cast",
            Self::SiegeCreate             => "Siege create",
            Self::SiegeAreaEffect         => "Siege area effect",
            Self::Defend                  => "Defend",
            Self::FreeInteract            => "Free interact",
            Self::ChangeAppearance        => "Change appearance",
            Self::AttackerReflect         => "Attacker reflect",
            Self::AttackerIntercept       => "Attacker intercept",
            Self::Disarm                  => "Disarm",
            Self::Parry                   => "Parry",
            Self::PathLine                => "Path line",
            Self::DoubleFire              => "Double fire",
            Self::FireProc                => "Fire proc",
            Self::Leap                    => "Leap",
            Self::Reveal                  => "Reveal",
            Self::SiegePackUp             => "Siege pack up",
            Self::Recall                  => "Recall",
            Self::GrantAbility            => "Grant ability",
            Self::Hide                    => "Hide",
            Self::SetHotbar               => "Set hotbar",
            Self::NoLockPick              => "No lock pick",
            Self::FillSoulGem             => "Fill soul gem",
            Self::SoulGemResurrect        => "Soul gem resurrect",
            Self::DespawnOverride         => "Despawn override",
            Self::UpdateDeathDialog       => "Update death dialog",
            Self::Deprecated4             => "Deprecated 4",
            Self::ClientFx                => "Client FX",
            Self::AvoidDeath              => "Avoid death",
            Self::NonCombatBonus          => "Non-combat bonus",
            Self::NoSeeTarget             => "No see target",
            Self::Deprecated              => "Deprecated",
            Self::SetPersonality          => "Set personality",
            Self::Basic                   => "Basic",
            Self::RewindTime              => "Rewind time",
            Self::LightHeavyAttackOverride => "Light/Heavy attack override",
            Self::DerivedStatCache        => "Derived stat cache",
            Self::AvAReach                => "AvA reach",
            Self::RandomBranch            => "Random branch",
            Self::MountBlock              => "Mount block",
            Self::Deprecated3             => "Deprecated 3",
            Self::HardDismount            => "Hard dismount",
            Self::LinkTarget              => "Link target",
            Self::CustomTargetArea        => "Custom target area",
            Self::DamageTransfer          => "Damage transfer",
            Self::DisableItemSets         => "Disable item sets",
            Self::FollowWaypointPath      => "Follow waypoint path",
            Self::SetAimAtTarget          => "Set aim at target",
            Self::FaceTarget              => "Face target",
            Self::LosMovePosition         => "LOS move position",
            Self::DisableClientTurning    => "Disable client turning",
            Self::DamageImmune            => "Damage immune",
            Self::StopMoving              => "Stop moving",
            Self::ResourceTap             => "Resource tap",
            Self::ShareUltimate           => "Share ultimate",
            Self::AvAObjectHeal           => "AvA object heal",
            Self::ReduceHealingFromOthers => "Reduce healing from others",
            Self::ReduceGravity           => "Reduce gravity",
            Self::NightMarketUnknown      => "Night market unknown",
            Self::MandatorySnare          => "Mandatory snare",
        }
    }
}

impl fmt::Display for AbilityType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TooltipType {
    ConditionalBuffActive,
    BuffGain,
    ActivationEffect,
    ResourceGain,
    MartialDamage,
    MagicalDamage,
    TickRate,
    Duration,
    DeprecatedChampionPoints,
    DeprecatedChampionPoints2,
    IncreasedDurationVsMonsters,
    MinimumCooldown,
    DeprecatedZeroDuration,
    SingleTargetDoT,
    DeprecatedMultiHit,
    SingleTargetHeal,
    AreaHoT,
    Percentage,
    IncreaseDurationOf,
    DeprecatedHalfSecondDuration,
    ReduceCostIncreaseRecovery,
    DeprecatedTriResourceGrant,
    DeprecatedArmourPercent,
    DeprecatedArmourMs,
    SelfHeal,
    Knockback,
    DeprecatedIncreasedChance,
    DelayedStrike,
    StatPercentage,
    ReduceHeatPercent,
    FlatConstant,
    PercentageConstant,
    ThresholdBelowHealthPercent,
    BonusUpToPercent,
    CompanionEffect,
    BuffExplanationText,
    BuffExplanationText2,
    MajorMinorBuffGain,
}

impl TooltipType {
    pub fn from_id(id: &u32) -> Option<Self> {
        match id {
            3   => Some(Self::ConditionalBuffActive),
            8   => Some(Self::BuffGain),
            10  => Some(Self::ActivationEffect),
            16  => Some(Self::ResourceGain),
            17  => Some(Self::MartialDamage),
            18  => Some(Self::MagicalDamage),
            19  => Some(Self::TickRate),
            20  => Some(Self::Duration),
            21  => Some(Self::DeprecatedChampionPoints),
            22  => Some(Self::DeprecatedChampionPoints2),
            31  => Some(Self::IncreasedDurationVsMonsters),
            44  => Some(Self::MinimumCooldown),
            48  => Some(Self::DeprecatedZeroDuration),
            49  => Some(Self::SingleTargetDoT),
            51  => Some(Self::DeprecatedMultiHit),
            52  => Some(Self::SingleTargetHeal),
            53  => Some(Self::AreaHoT),
            55  => Some(Self::Percentage),
            56  => Some(Self::IncreaseDurationOf),
            57  => Some(Self::DeprecatedHalfSecondDuration),
            58  => Some(Self::ReduceCostIncreaseRecovery),
            72  => Some(Self::DeprecatedTriResourceGrant),
            73  => Some(Self::DeprecatedArmourPercent),
            79  => Some(Self::DeprecatedArmourMs),
            90  => Some(Self::SelfHeal),
            91  => Some(Self::Knockback),
            92  => Some(Self::DeprecatedIncreasedChance),
            93  => Some(Self::DelayedStrike),
            96  => Some(Self::StatPercentage),
            97  => Some(Self::ReduceHeatPercent),
            99  => Some(Self::FlatConstant),
            100 => Some(Self::PercentageConstant),
            104 => Some(Self::ThresholdBelowHealthPercent),
            105 => Some(Self::BonusUpToPercent),
            114 => Some(Self::CompanionEffect),
            121 => Some(Self::BuffExplanationText),
            122 => Some(Self::BuffExplanationText2),
            123 => Some(Self::MajorMinorBuffGain),
            _   => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::ConditionalBuffActive       => "ConditionalBuffActive",
            Self::BuffGain                    => "BuffGain",
            Self::ActivationEffect            => "ActivationEffect",
            Self::ResourceGain                => "ResourceGain",
            Self::MartialDamage               => "MartialDamage",
            Self::MagicalDamage               => "MagicalDamage",
            Self::TickRate                    => "TickRate",
            Self::Duration                    => "Duration",
            Self::DeprecatedChampionPoints    => "DeprecatedChampionPoints",
            Self::DeprecatedChampionPoints2   => "DeprecatedChampionPoints2",
            Self::IncreasedDurationVsMonsters => "IncreasedDurationVsMonsters",
            Self::MinimumCooldown             => "MinimumCooldown",
            Self::DeprecatedZeroDuration      => "DeprecatedZeroDuration",
            Self::SingleTargetDoT             => "SingleTargetDoT",
            Self::DeprecatedMultiHit          => "DeprecatedMultiHit",
            Self::SingleTargetHeal            => "SingleTargetHeal",
            Self::AreaHoT                     => "AreaHoT",
            Self::Percentage                  => "Percentage",
            Self::IncreaseDurationOf          => "IncreaseDurationOf",
            Self::DeprecatedHalfSecondDuration => "DeprecatedHalfSecondDuration",
            Self::ReduceCostIncreaseRecovery  => "ReduceCostIncreaseRecovery",
            Self::DeprecatedTriResourceGrant  => "DeprecatedTriResourceGrant",
            Self::DeprecatedArmourPercent     => "DeprecatedArmourPercent",
            Self::DeprecatedArmourMs          => "DeprecatedArmourMs",
            Self::SelfHeal                    => "SelfHeal",
            Self::Knockback                   => "Knockback",
            Self::DeprecatedIncreasedChance   => "DeprecatedIncreasedChance",
            Self::DelayedStrike               => "DelayedStrike",
            Self::StatPercentage              => "StatPercentage",
            Self::ReduceHeatPercent           => "ReduceHeatPercent",
            Self::FlatConstant                => "FlatConstant",
            Self::PercentageConstant          => "PercentageConstant",
            Self::ThresholdBelowHealthPercent => "ThresholdBelowHealthPercent",
            Self::BonusUpToPercent            => "BonusUpToPercent",
            Self::CompanionEffect             => "CompanionEffect",
            Self::BuffExplanationText         => "BuffExplanationText",
            Self::BuffExplanationText2        => "BuffExplanationText2",
            Self::MajorMinorBuffGain          => "MajorMinorBuffGain",
        }
    }
}

impl fmt::Display for TooltipType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MajorMinorBuff {
    MinorBrutality,
    MajorBrutality,
    MinorSavagery,
    MajorSavagery,
    MinorSorcery,
    MajorSorcery,
    MinorProphecy,
    MajorProphecy,
    MinorResolve,
    MajorResolve,
    MinorBrittle,
    MinorFortitude,
    MajorEndurance,
    MinorEndurance,
    MajorFortitude,
    MinorHeroism,
    MajorHeroism,
    MinorMending,
    MajorMending,
    MinorVitality,
    MajorVitality,
    MinorEvasion,
    MajorEvasion,
    MinorProtection,
    MajorProtection,
    MinorMaim,
    MajorMaim,
    MinorDefile,
    MajorDefile,
    MinorExpedition,
    MajorExpedition,
    Empower,
    MinorBreach,
    MajorBreach,
    MinorBerserk,
    MajorBerserk,
    MinorForce,
    MajorForce,
    MajorCourage,
    MinorCourage,
    MinorToughness,
    Gallop,
    MinorEnervation,
    MinorUncertainty,
    MinorLifesteal,
    MinorMagickasteal,
    MinorVulnerability,
    MajorVulnerability,
}

impl MajorMinorBuff {
    pub fn from_id(id: &u32) -> Option<Self> {
        match id {
            1  => Some(Self::MinorBrutality),
            2  => Some(Self::MajorBrutality),
            3  => Some(Self::MinorSavagery),
            4  => Some(Self::MajorSavagery),
            5  => Some(Self::MinorSorcery),
            6  => Some(Self::MajorSorcery),
            7  => Some(Self::MinorProphecy),
            8  => Some(Self::MajorProphecy),
            9  => Some(Self::MinorResolve),
            10 => Some(Self::MajorResolve),
            11 => Some(Self::MinorBrittle),
            13 => Some(Self::MinorFortitude),
            14 => Some(Self::MajorEndurance),
            15 => Some(Self::MinorEndurance),
            16 => Some(Self::MajorFortitude),
            19 => Some(Self::MinorHeroism),
            20 => Some(Self::MajorHeroism),
            21 => Some(Self::MinorMending),
            22 => Some(Self::MajorMending),
            23 => Some(Self::MinorVitality),
            24 => Some(Self::MajorVitality),
            25 => Some(Self::MinorEvasion),
            26 => Some(Self::MajorEvasion),
            27 => Some(Self::MinorProtection),
            28 => Some(Self::MajorProtection),
            29 => Some(Self::MinorMaim),
            30 => Some(Self::MajorMaim),
            31 => Some(Self::MinorDefile),
            32 => Some(Self::MajorDefile),
            35 => Some(Self::MinorExpedition),
            36 => Some(Self::MajorExpedition),
            37 => Some(Self::Empower),
            40 => Some(Self::MinorBreach),
            41 => Some(Self::MajorBreach),
            42 => Some(Self::MinorBerserk),
            43 => Some(Self::MajorBerserk),
            44 => Some(Self::MinorForce),
            45 => Some(Self::MajorForce),
            46 => Some(Self::MajorCourage),
            48 => Some(Self::MinorCourage),
            50 => Some(Self::MinorToughness),
            54 => Some(Self::Gallop),
            55 => Some(Self::MinorEnervation),
            56 => Some(Self::MinorUncertainty),
            57 => Some(Self::MinorLifesteal),
            58 => Some(Self::MinorMagickasteal),
            60 => Some(Self::MinorVulnerability),
            61 => Some(Self::MajorVulnerability),
            _  => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::MinorBrutality    => "Minor Brutality",
            Self::MajorBrutality    => "Major Brutality",
            Self::MinorSavagery     => "Minor Savagery",
            Self::MajorSavagery     => "Major Savagery",
            Self::MinorSorcery      => "Minor Sorcery",
            Self::MajorSorcery      => "Major Sorcery",
            Self::MinorProphecy     => "Minor Prophecy",
            Self::MajorProphecy     => "Major Prophecy",
            Self::MinorResolve      => "Minor Resolve",
            Self::MajorResolve      => "Major Resolve",
            Self::MinorBrittle      => "Minor Brittle",
            Self::MinorFortitude    => "Minor Fortitude",
            Self::MajorEndurance    => "Major Endurance",
            Self::MinorEndurance    => "Minor Endurance",
            Self::MajorFortitude    => "Major Fortitude",
            Self::MinorHeroism      => "Minor Heroism",
            Self::MajorHeroism      => "Major Heroism",
            Self::MinorMending      => "Minor Mending",
            Self::MajorMending      => "Major Mending",
            Self::MinorVitality     => "Minor Vitality",
            Self::MajorVitality     => "Major Vitality",
            Self::MinorEvasion      => "Minor Evasion",
            Self::MajorEvasion      => "Major Evasion",
            Self::MinorProtection   => "Minor Protection",
            Self::MajorProtection   => "Major Protection",
            Self::MinorMaim         => "Minor Maim",
            Self::MajorMaim         => "Major Maim",
            Self::MinorDefile       => "Minor Defile",
            Self::MajorDefile       => "Major Defile",
            Self::MinorExpedition   => "Minor Expedition",
            Self::MajorExpedition   => "Major Expedition",
            Self::Empower           => "Empower",
            Self::MinorBreach       => "Minor Breach",
            Self::MajorBreach       => "Major Breach",
            Self::MinorBerserk      => "Minor Berserk",
            Self::MajorBerserk      => "Major Berserk",
            Self::MinorForce        => "Minor Force",
            Self::MajorForce        => "Major Force",
            Self::MajorCourage      => "Major Courage",
            Self::MinorCourage      => "Minor Courage",
            Self::MinorToughness    => "Minor Toughness",
            Self::Gallop            => "Gallop",
            Self::MinorEnervation   => "Minor Enervation",
            Self::MinorUncertainty  => "Minor Uncertainty",
            Self::MinorLifesteal    => "Minor Lifesteal",
            Self::MinorMagickasteal => "Minor Magickasteal",
            Self::MinorVulnerability => "Minor Vulnerability",
            Self::MajorVulnerability => "Major Vulnerability",
        }
    }

    pub fn tooltip_value(&self) -> u32 {
        match self {
            Self::MinorBrutality    => 10,
            Self::MajorBrutality    => 20,
            Self::MinorSavagery     => 1314,
            Self::MajorSavagery     => 2629,
            Self::MinorSorcery      => 10,
            Self::MajorSorcery      => 20,
            Self::MinorProphecy     => 1314,
            Self::MajorProphecy     => 2629,
            Self::MinorResolve      => 2974,
            Self::MajorResolve      => 5948,
            Self::MinorBrittle      => 10,
            Self::MinorFortitude    => 15,
            Self::MajorEndurance    => 30,
            Self::MinorEndurance    => 15,
            Self::MajorFortitude    => 30,
            Self::MinorHeroism      => 1,
            Self::MajorHeroism      => 3,
            Self::MinorMending      => 8,
            Self::MajorMending      => 16,
            Self::MinorVitality     => 6,
            Self::MajorVitality     => 12,
            Self::MinorEvasion      => 10,
            Self::MajorEvasion      => 20,
            Self::MinorProtection   => 5,
            Self::MajorProtection   => 10,
            Self::MinorMaim         => 5,
            Self::MajorMaim         => 10,
            Self::MinorDefile       => 6,
            Self::MajorDefile       => 12,
            Self::MinorExpedition   => 15,
            Self::MajorExpedition   => 30,
            Self::Empower           => 70,
            Self::MinorBreach       => 2974,
            Self::MajorBreach       => 5948,
            Self::MinorBerserk      => 5,
            Self::MajorBerserk      => 10,
            Self::MinorForce        => 10,
            Self::MajorForce        => 20,
            Self::MajorCourage      => 215,
            Self::MinorCourage      => 430,
            Self::MinorToughness    => 10,
            Self::Gallop            => 15,
            Self::MinorEnervation   => 10,
            Self::MinorUncertainty  => 1314,
            Self::MinorLifesteal    => 600,
            Self::MinorMagickasteal => 168,
            Self::MinorVulnerability => 5,
            Self::MajorVulnerability => 10,
        }
    }
}

impl fmt::Display for MajorMinorBuff {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SkillLine {
    // Weapon
    OneHandAndShield,
    TwoHanded,
    DualWield,
    Bow,
    DestructionStaff,
    RestorationStaff,
    // Armor
    LightArmour,
    MediumArmour,
    HeavyArmour,
    // Templar
    AedricSpear,
    DawnsWrath,
    RestoringLight,
    // Dragonknight
    ArdentFlame,
    DraconicPower,
    EarthenHeart,
    // Nightblade
    Assassination,
    Shadow,
    Siphoning,
    // Sorcerer
    DarkMagic,
    DaedricSummoning,
    StormCalling,
    // Warden
    AnimalCompanions,
    GreenBalance,
    WintersEmbrace,
    // Necromancer
    GraveLord,
    BoneTyrant,
    LivingDeath,
    // Arcanist
    HeraldOfTheTome,
    SoldierOfApocrypha,
    CurativeRuneforms,
    // Guild
    MagesGuild,
    FightersGuild,
    Undaunted,
    PsijicOrder,
    ThievesGuild,
    DarkBrotherhood,
    // Alliance War
    Assault,
    Support,
    Emperor,
    // Racial
    Orc,
    HighElf,
    WoodElf,
    Khajiit,
    Imperial,
    Breton,
    Redguard,
    Argonian,
    DarkElf,
    Nord,
    // World
    Werewolf,
    Vampire,
    SoulMagic,
    Legerdemain,
    Scrying,
    Excavation,
    // Crafting
    Provisioning,
    Alchemy,
    Enchanting,
    Blacksmithing,
    Woodworking,
    Clothing,
    Jewellery,


    // Companion - Bastian
    CompanionArdentWarrior,
    CompanionDraconicArmorBastian,
    CompanionRadiatingHeartBastian,
    // Companion - Mirri
    CompanionDeadlyAssassin,
    CompanionLivingShade,
    CompanionSoulThief,
    // Companion - Weapons & Armor
    CompanionTwoHanded,
    CompanionOneHandAndShield,
    CompanionDualWield,
    CompanionBow,
    CompanionDestructionStaff,
    CompanionRestorationStaff,
    CompanionLightArmor,
    CompanionMediumArmor,
    CompanionHeavyArmor,
    // Companion - Guilds
    CompanionFightersGuild,
    CompanionMagesGuild,
    CompanionUndaunted,
    // Companion - Racial
    CompanionImperial,
    CompanionDarkElf,
    CompanionHighElf,
    CompanionBreton,
    CompanionKhajiitEmber,
    CompanionRedguard,
    CompanionArgonian,
    CompanionKhajiitZerithVar,
    // Companion - Ember
    CompanionLightningCaller,
    CompanionMischievousCaster,
    CompanionPlayfulSchemer,
    // Companion - Isobel
    CompanionBlazingMight,
    CompanionBrilliantShield,
    CompanionHealingGrace,
    // Companion - Sharp
    CompanionBeastsOfTheHunt,
    CompanionWintersBite,
    CompanionVerdantGrowth,
    // Companion - Azandar
    CompanionScholarOfApocrypha,
    CompanionQuillKnight,
    CompanionRevitalizingResearcher,
    // Companion - Zerith-var
    CompanionWarriorsBanishment,
    CompanionRemedyOfAtonement,
    CompanionGuardiansCommitment,
    // Companion - Tanlorin
    CompanionRadiatingHeartTanlorin,
    CompanionDraconicArmorTanlorin,
    CompanionEmpathicFighter,


    // Vengeance
    VengeanceArdentFlame,
    VengeanceDraconicPower,
    VengeanceEarthenHeart,
    VengeanceAssassination,
    VengeanceShadow,
    VengeanceSiphoning,
    VengeanceAedricSpear,
    VengeanceDawnsWrath,
    VengeanceRestoringLight,
    VengeanceDaedricSummoning,
    VengeanceDarkMagic,
    VengeanceStormCalling,
    VengeanceAnimalCompanions,
    VengeanceGreenBalance,
    VengeanceWintersEmbrace,
    VengeanceGraveLord,
    VengeanceBoneTyrant,
    VengeanceLivingDeath,
    VengeanceCurativeRuneforms,
    VengeanceSoldierOfApocrypha,
    VengeanceHeraldOfTheTome,
    VengeanceTwoHanded,
    VengeanceOneHandAndShield,
    VengeanceDualWield,
    VengeanceBow,
    VengeanceDestructionStaff,
    VengeanceRestorationStaff,
    VengeanceAssault,
    VengeanceSupport,
    VengeanceFightersGuild,
    VengeanceMagesGuild,
    VengeanceUndaunted,

    // Misc
    PreU49DraconicPower,
}

impl SkillLine {
    pub fn from_id(id: &u32) -> Option<Self> {
        match id {
            29  => Some(Self::OneHandAndShield),
            30  => Some(Self::TwoHanded),
            31  => Some(Self::DualWield),
            32  => Some(Self::Bow),
            33  => Some(Self::DestructionStaff),
            34  => Some(Self::RestorationStaff),
            24  => Some(Self::LightArmour),
            25  => Some(Self::MediumArmour),
            26  => Some(Self::HeavyArmour),
            22  => Some(Self::AedricSpear),
            27  => Some(Self::DawnsWrath),
            28  => Some(Self::RestoringLight),
            35  => Some(Self::ArdentFlame),
            36  => Some(Self::DraconicPower),
            37  => Some(Self::EarthenHeart),
            38  => Some(Self::Assassination),
            39  => Some(Self::Shadow),
            40  => Some(Self::Siphoning),
            41  => Some(Self::DarkMagic),
            42  => Some(Self::DaedricSummoning),
            43  => Some(Self::StormCalling),
            127 => Some(Self::AnimalCompanions),
            128 => Some(Self::GreenBalance),
            129 => Some(Self::WintersEmbrace),
            131 => Some(Self::GraveLord),
            132 => Some(Self::BoneTyrant),
            133 => Some(Self::LivingDeath),
            218 => Some(Self::HeraldOfTheTome),
            219 => Some(Self::SoldierOfApocrypha),
            220 => Some(Self::CurativeRuneforms),
            44  => Some(Self::MagesGuild),
            45  => Some(Self::FightersGuild),
            55  => Some(Self::Undaunted),
            130 => Some(Self::PsijicOrder),
            117 => Some(Self::ThievesGuild),
            118 => Some(Self::DarkBrotherhood),
            48  => Some(Self::Assault),
            67  => Some(Self::Support),
            71  => Some(Self::Emperor),
            52  => Some(Self::Orc),
            56  => Some(Self::HighElf),
            57  => Some(Self::WoodElf),
            58  => Some(Self::Khajiit),
            59  => Some(Self::Imperial),
            60  => Some(Self::Breton),
            62  => Some(Self::Redguard),
            63  => Some(Self::Argonian),
            64  => Some(Self::DarkElf),
            65  => Some(Self::Nord),
            50  => Some(Self::Werewolf),
            51  => Some(Self::Vampire),
            72  => Some(Self::SoulMagic),
            111 => Some(Self::Legerdemain),
            155 => Some(Self::Scrying),
            157 => Some(Self::Excavation),
            76  => Some(Self::Provisioning),
            77  => Some(Self::Alchemy),
            78  => Some(Self::Enchanting),
            79  => Some(Self::Blacksmithing),
            80  => Some(Self::Woodworking),
            81  => Some(Self::Clothing),
            141 => Some(Self::Jewellery),
            174 => Some(Self::CompanionArdentWarrior),
            175 => Some(Self::CompanionDraconicArmorBastian),
            176 => Some(Self::CompanionRadiatingHeartBastian),
            177 => Some(Self::CompanionDeadlyAssassin),
            178 => Some(Self::CompanionLivingShade),
            179 => Some(Self::CompanionSoulThief),
            180 => Some(Self::CompanionTwoHanded),
            181 => Some(Self::CompanionOneHandAndShield),
            182 => Some(Self::CompanionDualWield),
            183 => Some(Self::CompanionBow),
            184 => Some(Self::CompanionDestructionStaff),
            185 => Some(Self::CompanionRestorationStaff),
            186 => Some(Self::CompanionLightArmor),
            187 => Some(Self::CompanionMediumArmor),
            188 => Some(Self::CompanionHeavyArmor),
            189 => Some(Self::CompanionFightersGuild),
            190 => Some(Self::CompanionMagesGuild),
            191 => Some(Self::CompanionUndaunted),
            192 => Some(Self::CompanionImperial),
            193 => Some(Self::CompanionDarkElf),
            267 => Some(Self::CompanionHighElf),
            203 => Some(Self::CompanionBreton),
            199 => Some(Self::CompanionKhajiitEmber),
            249 => Some(Self::CompanionRedguard),
            250 => Some(Self::CompanionArgonian),
            263 => Some(Self::CompanionKhajiitZerithVar),
            196 => Some(Self::CompanionLightningCaller),
            197 => Some(Self::CompanionMischievousCaster),
            198 => Some(Self::CompanionPlayfulSchemer),
            200 => Some(Self::CompanionBlazingMight),
            201 => Some(Self::CompanionBrilliantShield),
            202 => Some(Self::CompanionHealingGrace),
            241 => Some(Self::CompanionBeastsOfTheHunt),
            242 => Some(Self::CompanionWintersBite),
            243 => Some(Self::CompanionVerdantGrowth),
            246 => Some(Self::CompanionScholarOfApocrypha),
            247 => Some(Self::CompanionQuillKnight),
            248 => Some(Self::CompanionRevitalizingResearcher),
            260 => Some(Self::CompanionWarriorsBanishment),
            261 => Some(Self::CompanionRemedyOfAtonement),
            262 => Some(Self::CompanionGuardiansCommitment),
            264 => Some(Self::CompanionRadiatingHeartTanlorin),
            265 => Some(Self::CompanionDraconicArmorTanlorin),
            266 => Some(Self::CompanionEmpathicFighter),
            297 => Some(Self::VengeanceArdentFlame),
            298 => Some(Self::VengeanceDraconicPower),
            299 => Some(Self::VengeanceEarthenHeart),
            300 => Some(Self::VengeanceAssassination),
            301 => Some(Self::VengeanceShadow),
            302 => Some(Self::VengeanceSiphoning),
            303 => Some(Self::VengeanceAedricSpear),
            304 => Some(Self::VengeanceDawnsWrath),
            305 => Some(Self::VengeanceRestoringLight),
            306 => Some(Self::VengeanceDaedricSummoning),
            307 => Some(Self::VengeanceDarkMagic),
            308 => Some(Self::VengeanceStormCalling),
            309 => Some(Self::VengeanceAnimalCompanions),
            310 => Some(Self::VengeanceGreenBalance),
            311 => Some(Self::VengeanceWintersEmbrace),
            312 => Some(Self::VengeanceGraveLord),
            313 => Some(Self::VengeanceBoneTyrant),
            314 => Some(Self::VengeanceLivingDeath),
            315 => Some(Self::VengeanceCurativeRuneforms),
            316 => Some(Self::VengeanceSoldierOfApocrypha),
            317 => Some(Self::VengeanceHeraldOfTheTome),
            319 => Some(Self::VengeanceTwoHanded),
            320 => Some(Self::VengeanceOneHandAndShield),
            321 => Some(Self::VengeanceDualWield),
            322 => Some(Self::VengeanceBow),
            323 => Some(Self::VengeanceDestructionStaff),
            324 => Some(Self::VengeanceRestorationStaff),
            325 => Some(Self::VengeanceAssault),
            326 => Some(Self::VengeanceSupport),
            330 => Some(Self::VengeanceFightersGuild),
            331 => Some(Self::VengeanceMagesGuild),
            332 => Some(Self::VengeanceUndaunted),
            334 => Some(Self::PreU49DraconicPower),
            _   => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::OneHandAndShield               => "One Hand and Shield",
            Self::TwoHanded                      => "Two Handed",
            Self::DualWield                      => "Dual Wield",
            Self::Bow                            => "Bow",
            Self::DestructionStaff               => "Destruction Staff",
            Self::RestorationStaff               => "Restoration Staff",
            Self::LightArmour                    => "Light Armour",
            Self::MediumArmour                   => "Medium Armour",
            Self::HeavyArmour                    => "Heavy Armour",
            Self::AedricSpear                    => "Aedric Spear",
            Self::DawnsWrath                     => "Dawn's Wrath",
            Self::RestoringLight                 => "Restoring Light",
            Self::ArdentFlame                    => "Ardent Flame",
            Self::DraconicPower                  => "Draconic Power",
            Self::EarthenHeart                   => "Earthen Heart",
            Self::Assassination                  => "Assassination",
            Self::Shadow                         => "Shadow",
            Self::Siphoning                      => "Siphoning",
            Self::DarkMagic                      => "Dark Magic",
            Self::DaedricSummoning               => "Daedric Summoning",
            Self::StormCalling                   => "Storm Calling",
            Self::AnimalCompanions               => "Animal Companions",
            Self::GreenBalance                   => "Green Balance",
            Self::WintersEmbrace                 => "Winter's Embrace",
            Self::GraveLord                      => "Grave Lord",
            Self::BoneTyrant                     => "Bone Tyrant",
            Self::LivingDeath                    => "Living Death",
            Self::HeraldOfTheTome                => "Herald of the Tome",
            Self::SoldierOfApocrypha             => "Soldier of Apocrypha",
            Self::CurativeRuneforms              => "Curative Runeforms",
            Self::MagesGuild                     => "Mages Guild",
            Self::FightersGuild                  => "Fighters Guild",
            Self::Undaunted                      => "Undaunted",
            Self::PsijicOrder                    => "Psijic Order",
            Self::ThievesGuild                   => "Thieves Guild",
            Self::DarkBrotherhood                => "Dark Brotherhood",
            Self::Assault                        => "Assault",
            Self::Support                        => "Support",
            Self::Emperor                        => "Emperor",
            Self::Orc                            => "Orc",
            Self::HighElf                        => "High Elf",
            Self::WoodElf                        => "Wood Elf",
            Self::Khajiit                        => "Khajiit",
            Self::Imperial                       => "Imperial",
            Self::Breton                         => "Breton",
            Self::Redguard                       => "Redguard",
            Self::Argonian                       => "Argonian",
            Self::DarkElf                        => "Dark Elf",
            Self::Nord                           => "Nord",
            Self::Werewolf                       => "Werewolf",
            Self::Vampire                        => "Vampire",
            Self::SoulMagic                      => "Soul Magic",
            Self::Legerdemain                    => "Legerdemain",
            Self::Scrying                        => "Scrying",
            Self::Excavation                     => "Excavation",
            Self::Provisioning                   => "Provisioning",
            Self::Alchemy                        => "Alchemy",
            Self::Enchanting                     => "Enchanting",
            Self::Blacksmithing                  => "Blacksmithing",
            Self::Woodworking                    => "Woodworking",
            Self::Clothing                       => "Clothing",
            Self::Jewellery                      => "Jewellery",
            Self::CompanionArdentWarrior         => "Companion Ardent Warrior",
            Self::CompanionDraconicArmorBastian  => "Companion Draconic Armor (Bastian)",
            Self::CompanionRadiatingHeartBastian => "Companion Radiating Heart (Bastian)",
            Self::CompanionDeadlyAssassin        => "Companion Deadly Assassin",
            Self::CompanionLivingShade           => "Companion Living Shade",
            Self::CompanionSoulThief             => "Companion Soul Thief",
            Self::CompanionTwoHanded             => "Companion Two Handed",
            Self::CompanionOneHandAndShield      => "Companion One Hand and Shield",
            Self::CompanionDualWield             => "Companion Dual Wield",
            Self::CompanionBow                   => "Companion Bow",
            Self::CompanionDestructionStaff      => "Companion Destruction Staff",
            Self::CompanionRestorationStaff      => "Companion Restoration Staff",
            Self::CompanionLightArmor            => "Companion Light Armor",
            Self::CompanionMediumArmor           => "Companion Medium Armor",
            Self::CompanionHeavyArmor            => "Companion Heavy Armor",
            Self::CompanionFightersGuild         => "Companion Fighters Guild",
            Self::CompanionMagesGuild            => "Companion Mages Guild",
            Self::CompanionUndaunted             => "Companion Undaunted",
            Self::CompanionImperial              => "Companion Imperial",
            Self::CompanionDarkElf               => "Companion Dark Elf",
            Self::CompanionHighElf               => "Companion High Elf",
            Self::CompanionBreton                => "Companion Breton",
            Self::CompanionKhajiitEmber          => "Companion Khajiit (Ember)",
            Self::CompanionRedguard              => "Companion Redguard",
            Self::CompanionArgonian              => "Companion Argonian",
            Self::CompanionKhajiitZerithVar      => "Companion Khajiit (Zerith-var)",
            Self::CompanionLightningCaller       => "Companion Lightning Caller",
            Self::CompanionMischievousCaster     => "Companion Mischievous Caster",
            Self::CompanionPlayfulSchemer        => "Companion Playful Schemer",
            Self::CompanionBlazingMight          => "Companion Blazing Might",
            Self::CompanionBrilliantShield       => "Companion Brilliant Shield",
            Self::CompanionHealingGrace          => "Companion Healing Grace",
            Self::CompanionBeastsOfTheHunt       => "Companion Beasts of the Hunt",
            Self::CompanionWintersBite           => "Companion Winter's Bite",
            Self::CompanionVerdantGrowth         => "Companion Verdant Growth",
            Self::CompanionScholarOfApocrypha    => "Companion Scholar of Apocrypha",
            Self::CompanionQuillKnight           => "Companion Quill Knight",
            Self::CompanionRevitalizingResearcher => "Companion Revitalizing Researcher",
            Self::CompanionWarriorsBanishment    => "Companion Warrior's Banishment",
            Self::CompanionRemedyOfAtonement     => "Companion Remedy of Atonement",
            Self::CompanionGuardiansCommitment   => "Companion Guardian's Commitment",
            Self::CompanionRadiatingHeartTanlorin => "Companion Radiating Heart (Tanlorin)",
            Self::CompanionDraconicArmorTanlorin => "Companion Draconic Armor (Tanlorin)",
            Self::CompanionEmpathicFighter       => "Companion Empathic Fighter",
            Self::VengeanceArdentFlame           => "Vengeance Ardent Flame",
            Self::VengeanceDraconicPower         => "Vengeance Draconic Power",
            Self::VengeanceEarthenHeart          => "Vengeance Earthen Heart",
            Self::VengeanceAssassination         => "Vengeance Assassination",
            Self::VengeanceShadow                => "Vengeance Shadow",
            Self::VengeanceSiphoning             => "Vengeance Siphoning",
            Self::VengeanceAedricSpear           => "Vengeance Aedric Spear",
            Self::VengeanceDawnsWrath            => "Vengeance Dawn's Wrath",
            Self::VengeanceRestoringLight        => "Vengeance Restoring Light",
            Self::VengeanceDaedricSummoning      => "Vengeance Daedric Summoning",
            Self::VengeanceDarkMagic             => "Vengeance Dark Magic",
            Self::VengeanceStormCalling          => "Vengeance Storm Calling",
            Self::VengeanceAnimalCompanions      => "Vengeance Animal Companions",
            Self::VengeanceGreenBalance          => "Vengeance Green Balance",
            Self::VengeanceWintersEmbrace        => "Vengeance Winter's Embrace",
            Self::VengeanceGraveLord             => "Vengeance Grave Lord",
            Self::VengeanceBoneTyrant            => "Vengeance Bone Tyrant",
            Self::VengeanceLivingDeath           => "Vengeance Living Death",
            Self::VengeanceCurativeRuneforms     => "Vengeance Curative Runeforms",
            Self::VengeanceSoldierOfApocrypha    => "Vengeance Soldier of Apocrypha",
            Self::VengeanceHeraldOfTheTome       => "Vengeance Herald of the Tome",
            Self::VengeanceTwoHanded             => "Vengeance Two Handed",
            Self::VengeanceOneHandAndShield      => "Vengeance One Hand and Shield",
            Self::VengeanceDualWield             => "Vengeance Dual Wield",
            Self::VengeanceBow                   => "Vengeance Bow",
            Self::VengeanceDestructionStaff      => "Vengeance Destruction Staff",
            Self::VengeanceRestorationStaff      => "Vengeance Restoration Staff",
            Self::VengeanceAssault               => "Vengeance Assault",
            Self::VengeanceSupport               => "Vengeance Support",
            Self::VengeanceFightersGuild         => "Vengeance Fighters Guild",
            Self::VengeanceMagesGuild            => "Vengeance Mages Guild",
            Self::VengeanceUndaunted             => "Vengeance Undaunted",
            Self::PreU49DraconicPower            => "Pre-U49 Draconic Power",
        }
    }

    pub fn is_vengeance(&self) -> bool {
        matches!(self, Self::VengeanceArdentFlame | Self::VengeanceDraconicPower | Self::VengeanceEarthenHeart | Self::VengeanceAssassination | Self::VengeanceShadow | Self::VengeanceSiphoning | Self::VengeanceAedricSpear | Self::VengeanceDawnsWrath | Self::VengeanceRestoringLight | Self::VengeanceDaedricSummoning | Self::VengeanceDarkMagic | Self::VengeanceStormCalling | Self::VengeanceAnimalCompanions | Self::VengeanceGreenBalance | Self::VengeanceWintersEmbrace | Self::VengeanceGraveLord | Self::VengeanceBoneTyrant | Self::VengeanceLivingDeath | Self::VengeanceCurativeRuneforms | Self::VengeanceSoldierOfApocrypha | Self::VengeanceHeraldOfTheTome | Self::VengeanceTwoHanded | Self::VengeanceOneHandAndShield | Self::VengeanceDualWield | Self::VengeanceBow | Self::VengeanceDestructionStaff | Self::VengeanceRestorationStaff | Self::VengeanceAssault | Self::VengeanceSupport | Self::VengeanceFightersGuild | Self::VengeanceMagesGuild | Self::VengeanceUndaunted) 
    }
}

impl fmt::Display for SkillLine {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
